//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRendiciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoParticipante
    {
        public int CursoId { get; set; }
        public int ParticipanteId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public decimal Efectivo { get; set; }
        public decimal DepositooTransferencia { get; set; }
        public decimal Cheque { get; set; }
        public decimal TarjetaCredito { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
