//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRendiciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoGastoDetalle
    {
        public int EventoId { get; set; }
        public int ConsecutivoId { get; set; }
        public int ComprobanteTipoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int SubConceptoId { get; set; }
        public string Descripcion { get; set; }
        public string Proveedor { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
    
        public virtual ComprobanteTipo ComprobanteTipo { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual SubConcepto SubConcepto { get; set; }
    }
}
