//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRendiciones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIVHEntities : DbContext
    {
        public AIVHEntities()
            : base("name=AIVHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CentroCosto> CentroCosto { get; set; }
        public virtual DbSet<ComprobanteTipo> ComprobanteTipo { get; set; }
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<CursoGastoDetalle> CursoGastoDetalle { get; set; }
        public virtual DbSet<CursoParticipante> CursoParticipante { get; set; }
        public virtual DbSet<CursoTipo> CursoTipo { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoDonante> EventoDonante { get; set; }
        public virtual DbSet<EventoGastoDetalle> EventoGastoDetalle { get; set; }
        public virtual DbSet<EventoTipo> EventoTipo { get; set; }
        public virtual DbSet<Gasto> Gasto { get; set; }
        public virtual DbSet<GastoDetalle> GastoDetalle { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<SubConcepto> SubConcepto { get; set; }
        public virtual DbSet<SubMenu> SubMenu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
        public virtual DbSet<UsuarioRolAcceso> UsuarioRolAcceso { get; set; }
    }
}
