//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRendiciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMenu()
        {
            this.UsuarioRolAcceso = new HashSet<UsuarioRolAcceso>();
        }
    
        public int MenuId { get; set; }
        public int SubMenuId { get; set; }
        public string Descripcion { get; set; }
        public string Link { get; set; }
        public int EstatusId { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRolAcceso> UsuarioRolAcceso { get; set; }
    }
}
