//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRendiciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRolAcceso
    {
        public int UsuarioRolId { get; set; }
        public int SubMenuId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
    
        public virtual SubMenu SubMenu { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual UsuarioRol UsuarioRol { get; set; }
    }
}
